Directories:
    SystemUnderTest: system-under-test
    Instrumented: instrumented
    Examples: examples
    Findings: findings

Execute:
    Executable: JsonNetTest.exe
    Input: OnCommandLine

Instrument:
    Include:
        - "*.exe"
        - "*.dll"
    Exclude:
        - Fizil.Properties.dll
        - Mono.Cecil.dll
        - Mono.Cecil.Rocks.dll
        - TinyTest.vshost.exe

TextFileExtensions: 
    - .txt