Directories:
    SystemUnderTest: system-under-test
    Instrumented: instrumented
    Examples: examples

Execute:
    Executable: JsonNetTest.exe
    Input: onStandardInput
    Isolation: InProcessSerial

Instrument:
    Include:
        - "*.exe"
        - "*.dll"
    Exclude:
        - Fizil.Properties.dll
        - FSharp.Core.dll
        - Mono.Cecil.dll
        - Mono.Cecil.Rocks.dll
        - TinyTest.vshost.exe
        - StJson.exe

TextFileExtensions: 
    - .txt